import * as THREE from 'three';
import { Player } from './player.js';
import { MapGenerator } from '../Map/mapGenerator.js';

const panels={title:document.getElementById('menu-title'),worlds:document.getElementById('menu-worlds'),mods:document.getElementById('menu-mods'),skin:document.getElementById('menu-skin'),settings:document.getElementById('menu-settings')};
function showScreen(k){Object.values(panels).forEach(p=>p?.classList.add('hidden'));panels[k]?.classList.remove('hidden')}
function bind(id,fn){document.getElementById(id)?.addEventListener('click',e=>{e.stopPropagation();e.preventDefault();fn(e)})}
bind('btn-worlds',()=>showScreen('worlds'));bind('btn-mods',()=>showScreen('mods'));bind('btn-skin',()=>showScreen('skin'));bind('btn-settings',()=>showScreen('settings'));document.querySelectorAll('.btn-back').forEach(b=>b.onclick=()=>showScreen('title'));
let selectedSkin='default';document.querySelectorAll('.skin-card').forEach(c=>c.onclick=()=>{document.querySelectorAll('.skin-card').forEach(x=>x.classList.remove('selected'));c.classList.add('selected');selectedSkin=c.dataset.skin;document.getElementById('skin-status').textContent=`Active Skin: ${selectedSkin.toUpperCase()}`});
const input=document.getElementById('mod-file-input'),list=document.getElementById('loaded-mods-list');input?.addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=ev=>{try{const s=document.createElement('script');s.textContent=ev.target.result;document.body.appendChild(s);list.textContent=`Active Mod: ${f.name}`}catch(err){console.error(err);alert('Failed to run mod file.')}};r.readAsText(f)});
const inventory=[{name:'Grass',key:'grass',color:'#557a2b'},{name:'Gray',key:'gray',color:'#808080'},{name:'Blue',key:'blue',color:'#1e90ff'},{name:'Red',key:'red',color:'#ff3333'},{name:'Pink',key:'pink',color:'#ff69b4'},{name:'Green',key:'green',color:'#2e8b57'},{name:'Lime',key:'lime',color:'#32cd32'},{name:'Yellow',key:'yellow',color:'#ffd700'}];let slot=0;
function hotbar(){const h=document.getElementById('hotbar');h.innerHTML='';inventory.forEach((i,n)=>{const s=document.createElement('div');s.className='hotbar-slot '+(n===slot?'active':'');s.innerHTML=`<span class="hotbar-number">${n+1}</span><div class="hotbar-color-preview" style="background:${i.color}"></div>`;h.appendChild(s)})}function selectSlot(n){if(n>=0&&n<inventory.length){slot=n;hotbar()}}hotbar();window.addEventListener('keydown',e=>{const n=parseInt(e.key);if(n>=1&&n<=8)selectSlot(n-1)});
let started=false,player=null,map=null;const scene=new THREE.Scene();scene.background=new THREE.Color(0x87ceeb);const camera=new THREE.PerspectiveCamera(75,innerWidth/innerHeight,.1,1000);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;document.body.appendChild(renderer.domElement);const light=new THREE.DirectionalLight(0xffffff,1);light.position.set(30,50,30);light.castShadow=true;scene.add(light);scene.add(new THREE.AmbientLight(0xffffff,.5));
const fov=document.getElementById('fov-slider');fov.oninput=e=>{document.getElementById('fov-value').textContent=e.target.value;camera.fov=+e.target.value;camera.updateProjectionMatrix()};
function launch(){if(!started){map=new MapGenerator(scene,`PE_${Math.floor(Math.random()*99999)}`);map.generate();player=new Player(scene,camera,map);started=true}document.getElementById('ui-overlay').classList.add('hidden');renderer.domElement.requestPointerLock()}bind('btn-play-world',launch);
document.addEventListener('pointerlockchange',()=>{if(document.pointerLockElement!==renderer.domElement){document.getElementById('ui-overlay').classList.remove('hidden');showScreen('title')}});renderer.domElement.onclick=()=>{if(started&&document.pointerLockElement!==renderer.domElement)renderer.domElement.requestPointerLock()};
window.addEventListener('contextmenu',e=>e.preventDefault());window.addEventListener('wheel',e=>{if(document.pointerLockElement===renderer.domElement)selectSlot((slot+(e.deltaY>0?1:-1)+inventory.length)%inventory.length)});
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});const clock=new THREE.Clock();function animate(){requestAnimationFrame(animate);const d=Math.min(clock.getDelta(),.1);if(started&&player)player.update(d);else{const t=clock.getElapsedTime()*.15;camera.position.set(Math.sin(t)*25,18,Math.cos(t)*25);camera.lookAt(0,2,0)}renderer.render(scene,camera)}animate();
