import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
export class Player{constructor(scene,camera,map){this.scene=scene;this.camera=camera;this.mapGenerator=map;this.scale=.5;this.height=.9;this.eyeHeight=.8;this.position=new THREE.Vector3(0,20,0);this.velocity=new THREE.Vector3();this.moveSpeed=8;this.jumpForce=10;this.gravity=28;this.isGrounded=false;this.pitch=0;this.yaw=0;this.keys={forward:false,backward:false,left:false,right:false,jump:false};this.raycaster=new THREE.Raycaster();this.reachDistance=8;this.model=null;this.loadModel();this.controls()}
loadModel(){new GLTFLoader().load('https://raw.githubusercontent.com/jergan-studio/JergBuilder/main/jergplr.glb',g=>{this.model=g.scene;this.model.scale.setScalar(this.scale);this.scene.add(this.model);this.model.visible=false},undefined,e=>console.warn(e))}
controls(){addEventListener('keydown',e=>{this.key(e.code,true);if(e.code==='BracketLeft'&&this.model)this.model.visible=!this.model.visible});addEventListener('keyup',e=>this.key(e.code,false));addEventListener('mousemove',e=>{if(document.pointerLockElement){this.yaw-=e.movementX*.002;this.pitch-=e.movementY*.002;this.pitch=Math.max(-Math.PI/2.05,Math.min(Math.PI/2.05,this.pitch))}});addEventListener('mousedown',e=>{if(!document.pointerLockElement)return;const hit=this.getLookAtBlock();if(!hit)return;if(e.button===0)this.mapGenerator.removeBlock(hit.targetBlock.x,hit.targetBlock.y,hit.targetBlock.z);if(e.button===2)this.mapGenerator.addBlock(hit.placeBlock.x,hit.placeBlock.y,hit.placeBlock.z,this.mapGenerator.materials.grass)})}
key(c,v){if(c==='KeyW'||c==='ArrowUp')this.keys.forward=v;if(c==='KeyS'||c==='ArrowDown')this.keys.backward=v;if(c==='KeyA'||c==='ArrowLeft')this.keys.left=v;if(c==='KeyD'||c==='ArrowRight')this.keys.right=v;if(c==='Space')this.keys.jump=v}
getLookAtBlock(){const m=this.mapGenerator.worldBlocks;if(!m.length)return null;const origin=this.position.clone();origin.y+=this.eyeHeight;const dir=new THREE.Vector3(0,0,-1).applyEuler(new THREE.Euler(this.pitch,this.yaw,0,'YXZ'));this.raycaster.set(origin,dir);this.raycaster.far=this.reachDistance;const hits=this.raycaster.intersectObjects(m,true);if(!hits.length)return null;const h=hits[0],n=h.face?h.face.normal.clone():new THREE.Vector3(0,1,0);n.applyQuaternion(h.object.getWorldQuaternion(new THREE.Quaternion()));return{targetBlock:new THREE.Vector3(Math.floor(h.point.x-n.x*.4),Math.floor(h.point.y-n.y*.4),Math.floor(h.point.z-n.z*.4)),placeBlock:new THREE.Vector3(Math.floor(h.point.x+n.x*.4),Math.floor(h.point.y+n.y*.4),Math.floor(h.point.z+n.z*.4))}}
resolve(){if(!this.mapGenerator.worldBlocks.length)return;this.raycaster.set(this.position.clone().add(new THREE.Vector3(0,.4,0)),new THREE.Vector3(0,-1,0));this.raycaster.far=.5;const hits=this.raycaster.intersectObjects(this.mapGenerator.worldBlocks,true);if(hits.length&&this.velocity.y<=0){this.position.y=hits[0].point.y;this.velocity.y=0;this.isGrounded=true}else this.isGrounded=false}
update(d){const v=new THREE.Vector3((this.keys.right?1:0)-(this.keys.left?1:0),0,(this.keys.backward?1:0)-(this.keys.forward?1:0)).normalize().applyEuler(new THREE.Euler(0,this.yaw,0));this.velocity.x=v.x*this.moveSpeed;this.velocity.z=v.z*this.moveSpeed;if(this.isGrounded&&this.keys.jump){this.velocity.y=this.jumpForce;this.isGrounded=false}this.velocity.y-=this.gravity*d;this.position.addScaledVector(this.velocity,d);this.resolve();if(this.position.y<-30){this.position.set(0,20,0);this.velocity.set(0,0,0)}this.camera.position.set(this.position.x,this.position.y+this.eyeHeight,this.position.z);this.camera.quaternion.setFromEuler(new THREE.Euler(this.pitch,this.yaw,0,'YXZ'));if(this.model){this.model.position.copy(this.position);this.model.rotation.y=this.yaw}}}
